defaults:
  - base

system:
  CUDA_VISIBLE_DEVICES: "0,1,2,3"

trainer:
  experiment_name: 2048
  n_gpus_per_node: 4

actor_rollout_ref:
  rollout:
    response_length: 500
    val_kwargs:
      do_sample: True
      temperature: 0.5 # enabling randomness in evaluation 
 
agent_proxy:
  max_turn: 25
  max_actions_per_turn: 4
  max_context_window: 5

es_manager:
  train:
    env_configs:
      tags: ["rubikscube"]
  val:
    env_configs:
      tags: ["rubikscube"]
