defaults:
  - base

trainer:
  experiment_name: sudoku-main

actor_rollout_ref:
  rollout:
    response_length: 500

es_manager:
  train:
    env_groups: 8
    group_size: 16
    env_configs:
      tags: ["SimpleSudoku"]
      n_groups: [8]
  val:
    env_groups: 32
    group_size: 16
    env_configs:
      tags: ["SimpleSudoku"]
      n_groups: [32]